var excuse = [
  "I need to get more feedback first",
  "I don’t have time for that",
  "I can't afford to right now",
  "that might work for some people, but not for me",
  "It's not the right time",
  "I don't know if that's what I want",
  "I live in a small city",
  "I live in a big city",
  "my spouse won't support me",
  "I have to think of my children",
  "I don't know how to",
  "I don't have the looks",
  "I don’t have the right degree",
  "I’m a minority",
  "I’m overweight",
  "I Need to Focus on My Career",
  "I don't have the thing I need",
  "my family is my top priority",
  "I haven't finished planning yet",
  "my life is too complicated at the moment",
  "the Starbucks I normally go to isn't open",
  "I have too many urgent things to do",
  "that's not my job",
  "I don't have persmission",
  "it's too risky",
  "I don't know the right people",
  "I'm worried about what Raheem would say",
  "I hit a wall",
  "My dog died",
  "My cat died",
  "I have surgey that day",
  "I have anal fissures",
  "I left my medication at home",
  "I'm off my medication",
  "Luigi said I shouldn't",
  "I'm not smart enough",
  "it's raining",
  "it's snowing",
  "I'm drunk",
  "it's 3am",
  "it's 2am",
  "it's 4am",
  "I'm playing Mario Kart",
  "I have explosive diarrha",
  "I lost my dentures",
  "my hot water isn't working",
  "I had a burrito for dinner and I should have saved half of it but I'm too much of a big fat fatty fat to stop eating",
  "I've fallen and I can't get up",
  "my cat is asleep on my lap",
  "my dog ate my toothbrush and I can't leave the house with morning breath",
  "my neighbor just broke into my house",
  "I'm stuck on the roof",
  "my tires got stolen",
  "I'm under house arrest",
  "I'm in jail",
  "I did a split during yoga and I still can't get up...",
  "my OBGYN says I really shouldn't do that any more",
  "I fled the country",
  "I’m too upset about the state of the country",
  "I flushed my keys down the toilet",
  "I grew a tail",
  "my goldfish hasn't gotten her full eight hours of sleep",
  "a witch cursed me and I haven't discovered how to dispell it yet",
  "my pet snake is molting",
  "my pet bird is molting",
  "I'm getting married",
  "I'm getting divorced",
  "Julie left me",
  "I'm supposed to star in Hamilton tonight and I still haven't learned my lines",
  "I'm not wearing any pants",
  "you're not wearing any pants",
  "All of my clothes shrunk in the dryer",
  "my butt looks too fat in these pants",
  "I need to go floss",
  "I ripped my pants",
  "I'm in love with your mother",
  "it's time for happy hour",
];
var getExcuses = function () {
  var newExcuse = excuse[Math.floor(Math.random() * excuse.length)];
  document.getElementById("excuseHere").innerHTML = newExcuse;
};
