var excuse = [
  "my llama won't stop throwing up",
  "I accidentally switched my food and my cat's food and it turns out I'm severely allergic to tuna",
  "I got stuck in the blood pressure machine at the grocery store",
  "that might work for some people, but not for me",
  "my partner found out I was cheating and I'm busy retrieving my belongings from the dumpster",
  "my fortune teller said I shouldn't step out of the house or I would suffer a brain hemorrhage",
  "I accidentally got on a plane to Mexico City",
  "the souffle I cooked for my friend's potluck didn't turn out well",
  "I got lucky last night and I have no clue where I am now",
  "I put petroleum jelly in my eyes to see if I could absorb it and gain its powers",
  "I have to attend a funeral for my wife's cousin's pet. I'm an uncle and a pallbearer",
  "someone glued my doors and windows shut",
  "my teeth flew out of the car while I was driving with the windows down",
  "my pet iguana, Geraldine, is sick as a dog",
  "the ozone in the air flattened my tires",
  "I'm bowling the game of my life right now",
  "I've been at the casino all weekend and I still have money left to play",
  "I have a bat stuck in my wig",
  "I got bit by a duck",
  "I'm having traumatic stress from a big spider I found in the bathroom under the toilet seat",
  "the Starbucks I normally go to isn't open",
  "my uniform caught fire when I tried to dry it in the microwave",
  "I'm in a good mood right now and I don't want to ruin it",
  "I have a mint stuck up my nose and I have to go to the ER to get it removed",
  "my grandmother's body was exhumed for a police investigation",
  "I accidentally drove to my old office, even though I haven't worked there for five years",
  "I'm worried about what Raheem would think",
  "I swapped bodies with a crash test dummy and I'm stuck in car accidents the rest of the afternoon",
  "I'm too upset after watching \"The Hunger Games\"",
  "my cat wants to go to the amusement park",
  "I'm currently in surgery",
  "I have anal fissures",
  "I have too many garage sales to hit",
  "I have to cut the grass, or else I'll get fined by my Homeowner's Association",
  "Luigi said I shouldn't",
  "a cow broke into my 3rd floor apartment and it can't get down",
  "I forgot I got hired for the job",
  "I can't decide what to wear",
  "I have a gall stone that I'm trying to heal holistically",
  "I got a cold from my puppy",
  "I locked myself in my house by mistake and it doesn't have any windows to crawl out of",
  "I hurt my back chasing a beaver",
  "I'm on a hot streak playing pong",
  "I have explosive diarrhea",
  "I lost my dentures",
  "I got blocked in by a police raid next door",
  "I had a burrito for dinner and I should have saved half of it but I'm too much of a big fat fatty fat to stop eating",
  "I've fallen and I can't get up",
  "my cat is asleep on my lap",
  "my dog ate my toothbrush and I can't leave the house with morning breath",
  "my neighbor just broke into my house",
  "I'm stuck on the roof",
  "my tires got stolen",
  "I'm under house arrest",
  "I'm in jail",
  "I did a split during yoga and I still can't get up...",
  "my OBGYN says I really shouldn't do that any more",
  "I fled the country",
  "I’m too upset about the state of the country",
  "I flushed my keys down the toilet",
  "I thought Flag Day was a legal holiday",
  "my goldfish hasn't gotten her full eight hours of sleep",
  "a witch cursed me and I haven't discovered how to dispell it yet",
  "my pet snake is molting",
  "my pet bird is molting",
  "my mom locked me in the closet because I forgot to get her a Mother's Day gift",
  "my kids changed all the clocks in my house",
  "Julie left me",
  "I'm supposed to star in Hamilton tonight and I still haven't learned my lines",
  "I'm stuck on the back roads because my astrologer warned me of an accident on the highway",
  "you're not wearing any pants",
  "All of my clothes shrunk in the dryer",
  "my butt looks too fat in these pants",
  "I ordered a pizza I'm still waiting for and I have to be here when it arrives",
  "I ripped my pants",
  "I'm in love with your mother",
  "it's time for happy hour",
  "one of my butt cheeks fell asleep",
  "I have a blind date",
  "I have to do a blood ritual tonight",
  "I have an orgy to get to",
  "the janitor stole my fruit cup",
  "I have a dirty secret",
  "I have to go to a murder mystery party",
  "I'm not good at jiggly ball",
  "my fake eyelashes got stuck together",
  "I just bought this outfit",
  "my cousin peed in the pool",
  "there's a full moon tonight",
  "I fell asleep in the adult bookstore parking lot",
  "my spiritual advisor wouldn't approve",
  "I'm about to be arrested",
  "I broke my arm trying to steal my neighbor's kid's sandwich",
  "my fridge fell on me",
  "my car is covered in sticky notes",
  "I just put a casserole in the oven",
  "I'm cooking yams for my geriatric dog, Schnootzie",
  "my cat found out where I'm ticklish",
  "I broke my foot getting up from the toilet",
  "my grandma tried to poison me",
  "I fought the law and the law won"
];
var getExcuses = function () {
  var newExcuse = excuse[Math.floor(Math.random() * excuse.length)];
  document.getElementById("excuseHere").innerHTML = newExcuse;
};
